# GitLab CI/CD for Krepto - Working Configuration
image: ubuntu:22.04

stages:
  - test
  - build

variables:
  DEBIAN_FRONTEND: noninteractive

# Simple test to verify CI is working
test-basic:
  stage: test
  script:
    - echo "🔍 GitLab CI is working!"
    - echo "Project: $CI_PROJECT_NAME"
    - echo "Commit: $CI_COMMIT_SHA"
    - echo "Branch: $CI_COMMIT_REF_NAME"
    - apt-get update -qq
    - apt-get install -y build-essential git
    - echo "✅ Basic tools installed"
    - ls -la
    - echo "✅ Test completed successfully!"

# Linux build
build-linux:
  stage: build
  script:
    - echo "🐧 Building Krepto for Linux..."
    - apt-get update -qq
    - apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils python3
    - apt-get install -y libevent-dev libboost-dev libboost-system-dev libboost-filesystem-dev
    - apt-get install -y libboost-test-dev libboost-thread-dev libssl-dev
    - apt-get install -y libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools
    - apt-get install -y libqrencode-dev libzmq3-dev
    - echo "🔨 Starting build process..."
    - ./autogen.sh
    - ./configure --with-gui=qt5 --enable-reduce-exports --disable-tests --disable-bench
    - make -j2
    - echo "✅ Linux build completed!"
    - ls -la src/qt/bitcoin-qt src/bitcoind src/bitcoin-cli
  artifacts:
    paths:
      - src/qt/bitcoin-qt
      - src/bitcoind
      - src/bitcoin-cli
    expire_in: 1 week
  only:
    - main

# Windows cross-compilation build
build-windows:
  stage: build
  script:
    - echo "🪟 Building Krepto for Windows..."
    - apt-get update -qq
    - apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils python3
    - apt-get install -y g++-mingw-w64-x86-64 mingw-w64-x86-64-dev
    - update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
    - echo "🔨 Building dependencies..."
    - cd depends
    - make HOST=x86_64-w64-mingw32 -j2
    - cd ..
    - echo "🔨 Building Krepto..."
    - ./autogen.sh
    - CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
    - make -j2
    - echo "✅ Windows build completed!"
    - ls -la src/qt/bitcoin-qt.exe src/bitcoind.exe src/bitcoin-cli.exe
  artifacts:
    paths:
      - src/qt/bitcoin-qt.exe
      - src/bitcoind.exe
      - src/bitcoin-cli.exe
    expire_in: 1 week
  only:
    - main
  timeout: 3h 