# ==============================================================================
# Фінальний, оптимізований воркфлоу для CI/CD проєкту Krepto
# ==============================================================================
name: CI/CD Pipeline

on:
  # Запускати на Pull Request до будь-якої гілки
  pull_request:
  # Запускати на Push до гілок main та develop
  push:
    branches:
      - 'main'
      - 'develop'
  # Дозволяє запускати воркфлоу вручну з панелі GitHub Actions
  workflow_dispatch:

# Скасовує попередні запуски для того ж PR або гілки, щоб не витрачати ресурси
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # --- Збірка та тестування на Linux ---
  # Цей job компілює проєкт і запускає всі тести.
  # Він є основним для перевірки коректності коду.
  linux-build-and-test:
    name: 'Linux Build & Test'
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ccache clang build-essential libtool autotools-dev automake pkg-config \
            bsdmainutils python3-zmq libevent-dev libboost-dev libsqlite3-dev \
            libdb++-dev systemtap-sdt-dev libminiupnpc-dev libnatpmp-dev \
            qtbase5-dev qttools5-dev qttools5-dev-tools qtwayland5 libqrencode-dev

      - name: Configure ccache
        run: |
          echo "CCACHE_DIR=${{ github.workspace }}/.ccache" >> $GITHUB_ENV
          ccache --set-config=max_size=500M
          ccache --zero-stats

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-ccache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ github.ref }}-
            ${{ runner.os }}-ccache-main-
            ${{ runner.os }}-ccache-

      - name: Build and run tests
        run: |
          ./autogen.sh
          # Використовуємо ccache для значного прискорення повторних збірок
          CC="ccache clang" CXX="ccache clang++" ./configure --with-incompatible-bdb
          make -j$(nproc) check
          ./test/functional/test_runner.py -j$(( $(nproc) * 2 ))

      - name: Show ccache statistics
        if: always()
        run: ccache --show-stats

  # --- Збірка DMG для macOS ---
  # Створює інсталяційний DMG файл для macOS.
  macos-build:
    name: 'macOS Build (DMG)'
    runs-on: macos-13
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: |
          sudo xcode-select --switch /Applications/Xcode_15.0.app
          clang --version
      
      # Створюємо Brewfile "на льоту" для чистого кешування
      - name: Create Brewfile for caching
        run: |
          cat <<EOF > Brewfile
          brew "automake"
          brew "libtool"
          brew "pkg-config"
          brew "gnu-getopt"
          brew "ccache"
          brew "boost"
          brew "libevent"
          brew "miniupnpc"
          brew "libnatpmp"
          brew "zeromq"
          brew "qt@5"
          brew "qrencode"
          EOF
          
      - name: Cache Homebrew dependencies
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-brew-${{ hashFiles('**/Brewfile') }}
          restore-keys: ${{ runner.os }}-brew-

      - name: Install Homebrew packages
        run: |
          brew update
          brew bundle install

      - name: Configure ccache
        run: |
          echo "CCACHE_DIR=${{ github.workspace }}/.ccache" >> $GITHUB_ENV
          ccache --set-config=max_size=500M
          ccache --zero-stats
          # Додаємо ccache в PATH
          echo "$(brew --prefix)/opt/ccache/libexec" >> $GITHUB_PATH

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.ccache
          # Правильний ключ для ефективного кешування між запусками
          key: ${{ runner.os }}-ccache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ github.ref }}-
            ${{ runner.os }}-ccache-main-
            ${{ runner.os }}-ccache-

      - name: Configure and Build Krepto
        run: |
          # Динамічно визначаємо префікс Homebrew для підтримки Intel та Apple Silicon
          BREW_PREFIX=$(brew --prefix)
          echo "Homebrew prefix is: $BREW_PREFIX"

          # Встановлюємо правильні шляхи незалежно від архітектури
          export PATH="$BREW_PREFIX/bin:$PATH"
          export PKG_CONFIG_PATH="$BREW_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
          
          ./autogen.sh
          # Використовуємо ccache для прискорення та динамічний шлях до Qt
          ./configure CC="ccache clang" CXX="ccache clang++" \
            --enable-gui --disable-tests --disable-bench \
            --with-qt-bindir="$BREW_PREFIX/opt/qt@5/bin"
          make -j$(sysctl -n hw.ncpu)

      - name: Build Professional DMG
        # Повний скрипт створення DMG з динамічними шляхами
        run: |
          echo "🎨 Building Professional Krepto DMG Installer..."
          BREW_PREFIX=$(brew --prefix)
          
          rm -rf Krepto.app dmg_temp Krepto.dmg Krepto.dmg.sha256
          
          if [ ! -f "src/qt/bitcoin-qt" ]; then
              echo "❌ ERROR: Main executable 'src/qt/bitcoin-qt' not found! Build failed."
              exit 1
          fi
          
          mkdir -p Krepto.app/Contents/{MacOS,Resources}
          cp src/qt/bitcoin-qt Krepto.app/Contents/MacOS/Krepto
          
          cat > Krepto.app/Contents/Info.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleExecutable</key><string>Krepto</string>
              <key>CFBundleIdentifier</key><string>org.krepto.Krepto</string>
              <key>CFBundleName</key><string>Krepto</string>
              <key>CFBundleDisplayName</key><string>Krepto</string>
              <key>CFBundleVersion</key><string>1.0.0</string>
              <key>CFBundleShortVersionString</key><string>1.0</string>
              <key>CFBundlePackageType</key><string>APPL</string>
              <key>CFBundleSignature</key><string>KREP</string>
              <key>LSMinimumSystemVersion</key><string>10.14</string>
              <key>NSHighResolutionCapable</key><true/>
          </dict>
          </plist>
          EOF

          MACDEPLOYQT="$BREW_PREFIX/opt/qt@5/bin/macdeployqt"
          if [ ! -f "$MACDEPLOYQT" ]; then
            echo "❌ ERROR: macdeployqt not found at $MACDEPLOYQT"
            exit 1
          fi
          "$MACDEPLOYQT" Krepto.app -verbose=2
          
          cp src/bitcoind Krepto.app/Contents/MacOS/kryptod
          cp src/bitcoin-cli Krepto.app/Contents/MacOS/krypto-cli
          
          # ... (решта вашого скрипта створення DMG) ...

          mkdir -p dmg_temp
          cp -R Krepto.app dmg_temp/
          ln -s /Applications dmg_temp/Applications
          hdiutil create -volname "Krepto Installer" -srcfolder dmg_temp -ov -format UDRW temp_krepto.dmg
          hdiutil attach temp_krepto.dmg -mountpoint /Volumes/KreptoInstaller
          # Ваш AppleScript...
          hdiutil detach /Volumes/KreptoInstaller
          hdiutil convert temp_krepto.dmg -format UDZO -o Krepto.dmg
          rm -rf dmg_temp temp_krepto.dmg
          
          shasum -a 256 Krepto.dmg > Krepto.dmg.sha256

      - name: Show ccache statistics
        if: always()
        run: ccache --show-stats

      - name: Upload macOS DMG artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Krepto-macOS-DMG
          path: |
            Krepto.dmg
            Krepto.dmg.sha256
          retention-days: 30

  # --- Збірка для Windows ---
  # Оптимізована версія, що базується на вашому `build-windows-gui.yml`.
  # Використовує готову Qt та кешування vcpkg.
  windows-build:
    name: 'Windows Build (MSVC)'
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Встановлюємо готову збірку Qt, а не компілюємо з нуля. Економить ~20 хв.
    - name: Setup Qt5
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        cache: true # Цей екшн має власне ефективне кешування

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    # vcpkg кешується автоматично, якщо використовувати цей екшн
    - name: Setup vcpkg and install dependencies
      uses: lukka/run-vcpkg@v11
      with:
        # Пін версії vcpkg для стабільних збірок
        vcpkgGitCommitId: '7fbdc63d044dd7b5afda35c8adf71e9c749f6fc0'
        # Встановлюємо залежності. vcpkg автоматично кешує їх.
        vcpkgJsonGlob: 'build_msvc/vcpkg.json'

    - name: Generate Project Files
      run: py -3 build_msvc/msvc-autogen.py

    - name: Build with MSBuild
      run: msbuild build_msvc/bitcoin.sln -property:Configuration=Release -maxCpuCount -verbosity:minimal
      
    - name: Package Windows GUI
      shell: powershell
      run: |
        # Створюємо директорію для виводу
        New-Item -ItemType Directory -Force "output"
        
        # Копіюємо виконувані файли
        $releaseDir = "build_msvc/x64/Release"
        Copy-Item "$releaseDir/bitcoin-qt.exe" "output/krepto-qt.exe"
        Copy-Item "$releaseDir/bitcoind.exe" "output/kryptod.exe"
        Copy-Item "$releaseDir/bitcoin-cli.exe" "output/krepto-cli.exe"
        
        # Використовуємо windeployqt для автоматичного копіювання всіх потрібних DLL
        windeployqt.exe --release --no-translations output/krepto-qt.exe
        
        # Створюємо файл конфігурації та README...
        # (Ваш код для створення krepto.conf та README.txt)
      
    - name: Create ZIP package
      run: Compress-Archive -Path "output\*" -DestinationPath "Krepto-Windows-GUI.zip"

    - name: Upload Windows GUI artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Krepto-Windows-GUI
        path: Krepto-Windows-GUI.zip
        retention-days: 30